server:  
  port: ${PORT:8082}
#management.port: 8082 spring boot admin

spring:  
  application:
name: servicio-creditos


instance.id: ${random.value}


management:
  security:
    enabled: false

security:
  basic:
    enabled: false


#influx:
#  host: localhost
#  port: 8086
#  user: admin
#  password: admin
#  database: grafana
    