kind: Service
apiVersion: v1
metadata:
  name: servicio-creditos
spec:
  type: LoadBalancer
  selector:
    app: servicio-creditos
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
 

    

    